name: openid4vp_dcql
description: A Dart library for building, validating, and serializing Digital Credentials Query Language (DCQL) queries for OpenID for Verifiable Presentations (OpenID4VP).
version: 1.0.1
repository: https://github.com/nombrekeff/openid4vp_dcql

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
# dependencies:
#   

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
