name: openid4vp_dcql
description: A Dart library for building DCQL queries for OpenID4VP.
version: 1.0.0
repository: https://github.com/nombrekeff/openid4vp_dcql

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# dependencies:
#   

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
